version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.8.1

    environment:
      TEST_REPO_URL: "https://github.com/bilaldjedovic/pw-ui-test.git"

    steps:
      - checkout

      - run:
          name: Clone Test Repository
          command: git clone $TEST_REPO_URL

      - run:
          name: Install Test Dependencies
          command: |
            cd pw-ui-test
            npm install
            npx playwright install chromium
            sudo npx playwright install-deps

      - run:
          name: Run Regression Tests
          command: |
            cd pw-ui-test
            npx playwright test --project=chromium

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build_and_test
