version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.8.1

    environment:
      MAIN_REPO_URL: "https://github.com/bilaldjedovic/playwrigh-practice-app.git"
      TEST_REPO_URL: "https://github.com/bilaldjedovic/pw-ui-test.git"

    steps:
      - checkout

      - run:
          name: Checkout Main Repository
          command: git clone $MAIN_REPO_URL

      - run:
          name: Checkout Test Repository
          command: git clone $TEST_REPO_URL

      - run:
          name: Install Dependencies for Main Repository
          command: |
            cd playwrigh-practice-app
            npm install --force

      - run:
          name: Start Main Repository
          command: |
            cd playwrigh-practice-app # Adjust the directory based on your project structure
            npm start &
            sleep 160
      - run:
          name: Install Dependencies for Test Repository
          command: |
            cd pw-ui-test 
            npm install
            npx playwright install chromium
            sudo npx playwright install-deps

      - run:
          name: Run Regression Tests
          command: |
            cd pw-ui-test
            npx playwright test 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
